// Adapted from AndroidX Material 3, Apache-2.0. See docs/text-fields.md.
export type MaterialTextFieldVariant = 'filled' | 'outlined'
export type MaterialTextFieldColorMode = 'default' | 'tonal'
export type MaterialTextFieldColorState = 'focused' | 'unfocused' | 'disabled' | 'error'
export type MaterialTextFieldColorRole = 'Text' | 'Container' | 'Indicator' | 'LeadingIcon' | 'TrailingIcon' | 'Label' | 'Placeholder' | 'SupportingText' | 'Prefix' | 'Suffix'
export type MaterialTextFieldColors = Partial<Record<`${MaterialTextFieldColorState}${MaterialTextFieldColorRole}Color`, string>> & {
  cursorColor?: string
  errorCursorColor?: string
  textSelectionColors?: { handleColor?: string; backgroundColor?: string }
}

export const MATERIAL_TEXT_FIELD_DIMENSIONS = {
  minWidth: 280, minHeight: 56, iconSize: 24, iconTargetSize: 48,
  horizontalPadding: 16, verticalPadding: 16, insideLabelVerticalPadding: 8,
  affixGap: 2, aboveLabelHorizontalPadding: 4, aboveLabelBottomPadding: 4,
  supportingTopPadding: 4, supportingLineHeight: 16, cutoutPadding: 4,
  cutoutTopPadding: 8, unfocusedIndicatorThickness: 1, focusedIndicatorThickness: 2,
} as const

const filledDefault: MaterialTextFieldColors = {
  focusedTextColor: 'var(--md-sys-color-on-surface)',
  unfocusedTextColor: 'var(--md-sys-color-on-surface)',
  disabledTextColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorTextColor: 'var(--md-sys-color-on-surface)',
  focusedContainerColor: 'var(--md-sys-color-surface-container-highest)',
  unfocusedContainerColor: 'var(--md-sys-color-surface-container-highest)',
  disabledContainerColor: 'var(--md-sys-color-surface-container-highest)',
  errorContainerColor: 'var(--md-sys-color-surface-container-highest)',
  cursorColor: 'var(--md-sys-color-primary)',
  errorCursorColor: 'var(--md-sys-color-error)',
  focusedIndicatorColor: 'var(--md-sys-color-primary)',
  unfocusedIndicatorColor: 'var(--md-sys-color-on-surface-variant)',
  disabledIndicatorColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorIndicatorColor: 'var(--md-sys-color-error)',
  focusedLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  disabledLeadingIconColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  focusedTrailingIconColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedTrailingIconColor: 'var(--md-sys-color-on-surface-variant)',
  disabledTrailingIconColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorTrailingIconColor: 'var(--md-sys-color-error)',
  focusedLabelColor: 'var(--md-sys-color-primary)',
  unfocusedLabelColor: 'var(--md-sys-color-on-surface-variant)',
  disabledLabelColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorLabelColor: 'var(--md-sys-color-error)',
  focusedPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  disabledPlaceholderColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  focusedSupportingTextColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedSupportingTextColor: 'var(--md-sys-color-on-surface-variant)',
  disabledSupportingTextColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorSupportingTextColor: 'var(--md-sys-color-error)',
  focusedPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  disabledPrefixColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  errorPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  focusedSuffixColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedSuffixColor: 'var(--md-sys-color-on-surface-variant)',
  disabledSuffixColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  errorSuffixColor: 'var(--md-sys-color-on-surface-variant)',
}

const filledTonal: MaterialTextFieldColors = {
  unfocusedContainerColor: 'var(--md-sys-color-surface-container)',
  unfocusedIndicatorColor: 'transparent',
  unfocusedTextColor: 'var(--md-sys-color-on-surface)',
  unfocusedLabelColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedTrailingIconColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedSupportingTextColor: 'var(--md-sys-color-on-background)',
  unfocusedPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedSuffixColor: 'var(--md-sys-color-on-surface-variant)',
  focusedContainerColor: 'var(--md-sys-color-surface-container)',
  focusedIndicatorColor: 'transparent',
  focusedTextColor: 'var(--md-sys-color-on-background)',
  focusedLabelColor: 'var(--md-sys-color-on-surface-variant)',
  focusedLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  focusedTrailingIconColor: 'var(--md-sys-color-on-surface-variant)',
  focusedSupportingTextColor: 'var(--md-sys-color-on-background)',
  focusedPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  focusedPrefixColor: 'var(--md-sys-color-on-background)',
  focusedSuffixColor: 'var(--md-sys-color-on-background)',
  disabledContainerColor: 'color-mix(in srgb, var(--md-sys-color-surface-container) 38%, transparent)',
  disabledIndicatorColor: 'transparent',
  disabledTextColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  disabledLabelColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledLeadingIconColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledTrailingIconColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledSupportingTextColor: 'color-mix(in srgb, var(--md-sys-color-on-background) 38%, transparent)',
  disabledPlaceholderColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledPrefixColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledSuffixColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  errorContainerColor: 'var(--md-sys-color-error-container)',
  errorIndicatorColor: 'transparent',
  errorTextColor: 'var(--md-sys-color-on-background)',
  errorLabelColor: 'var(--md-sys-color-error)',
  errorLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  errorTrailingIconColor: 'var(--md-sys-color-error)',
  errorCursorColor: 'var(--md-sys-color-error)',
  errorSupportingTextColor: 'var(--md-sys-color-error)',
  errorPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  errorPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  errorSuffixColor: 'var(--md-sys-color-on-surface-variant)',
  cursorColor: 'var(--md-sys-color-primary)',
}

const outlinedDefault: MaterialTextFieldColors = {
  focusedTextColor: 'var(--md-sys-color-on-surface)',
  unfocusedTextColor: 'var(--md-sys-color-on-surface)',
  disabledTextColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorTextColor: 'var(--md-sys-color-on-surface)',
  focusedContainerColor: 'transparent',
  unfocusedContainerColor: 'transparent',
  disabledContainerColor: 'transparent',
  errorContainerColor: 'transparent',
  cursorColor: 'var(--md-sys-color-primary)',
  errorCursorColor: 'var(--md-sys-color-error)',
  focusedIndicatorColor: 'var(--md-sys-color-primary)',
  unfocusedIndicatorColor: 'var(--md-sys-color-outline)',
  disabledIndicatorColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 12%, transparent)',
  errorIndicatorColor: 'var(--md-sys-color-error)',
  focusedLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  disabledLeadingIconColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  focusedTrailingIconColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedTrailingIconColor: 'var(--md-sys-color-on-surface-variant)',
  disabledTrailingIconColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorTrailingIconColor: 'var(--md-sys-color-error)',
  focusedLabelColor: 'var(--md-sys-color-primary)',
  unfocusedLabelColor: 'var(--md-sys-color-on-surface-variant)',
  disabledLabelColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorLabelColor: 'var(--md-sys-color-error)',
  focusedPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  disabledPlaceholderColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  focusedSupportingTextColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedSupportingTextColor: 'var(--md-sys-color-on-surface-variant)',
  disabledSupportingTextColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  errorSupportingTextColor: 'var(--md-sys-color-error)',
  focusedPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  disabledPrefixColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  errorPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  focusedSuffixColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedSuffixColor: 'var(--md-sys-color-on-surface-variant)',
  disabledSuffixColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  errorSuffixColor: 'var(--md-sys-color-on-surface-variant)',
}

const outlinedTonal: MaterialTextFieldColors = {
  unfocusedContainerColor: 'transparent',
  unfocusedIndicatorColor: 'var(--md-sys-color-outline-variant)',
  unfocusedTextColor: 'var(--md-sys-color-on-surface)',
  unfocusedLabelColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedTrailingIconColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedSupportingTextColor: 'var(--md-sys-color-on-background)',
  unfocusedPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  unfocusedSuffixColor: 'var(--md-sys-color-on-surface-variant)',
  focusedContainerColor: 'transparent',
  focusedIndicatorColor: 'var(--md-sys-color-outline-variant)',
  focusedTextColor: 'var(--md-sys-color-on-background)',
  focusedLabelColor: 'var(--md-sys-color-on-surface-variant)',
  focusedLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  focusedTrailingIconColor: 'var(--md-sys-color-on-surface-variant)',
  focusedSupportingTextColor: 'var(--md-sys-color-on-background)',
  focusedPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  focusedPrefixColor: 'var(--md-sys-color-on-background)',
  focusedSuffixColor: 'var(--md-sys-color-on-background)',
  disabledContainerColor: 'transparent',
  disabledIndicatorColor: 'var(--md-sys-color-outline-variant)',
  disabledTextColor: 'color-mix(in srgb, var(--md-sys-color-on-surface) 38%, transparent)',
  disabledLabelColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledLeadingIconColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledTrailingIconColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledSupportingTextColor: 'color-mix(in srgb, var(--md-sys-color-on-background) 38%, transparent)',
  disabledPlaceholderColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledPrefixColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  disabledSuffixColor: 'color-mix(in srgb, var(--md-sys-color-on-surface-variant) 38%, transparent)',
  errorContainerColor: 'transparent',
  errorIndicatorColor: 'var(--md-sys-color-error)',
  errorTextColor: 'var(--md-sys-color-on-background)',
  errorLabelColor: 'var(--md-sys-color-error)',
  errorLeadingIconColor: 'var(--md-sys-color-on-surface-variant)',
  errorTrailingIconColor: 'var(--md-sys-color-error)',
  errorCursorColor: 'var(--md-sys-color-error)',
  errorSupportingTextColor: 'var(--md-sys-color-error)',
  errorPlaceholderColor: 'var(--md-sys-color-on-surface-variant)',
  errorPrefixColor: 'var(--md-sys-color-on-surface-variant)',
  errorSuffixColor: 'var(--md-sys-color-on-surface-variant)',
  cursorColor: 'var(--md-sys-color-primary)',
}

/** AndroidX color defaults. Overrides contain final colors, including any disabled alpha. */
export function getMaterialTextFieldColors(
  variant: MaterialTextFieldVariant = 'filled',
  colorMode: MaterialTextFieldColorMode = 'default',
): MaterialTextFieldColors {
  const colors = variant === 'filled'
    ? colorMode === 'tonal' ? filledTonal : filledDefault
    : colorMode === 'tonal' ? outlinedTonal : outlinedDefault
  return { ...colors, textSelectionColors: {
    handleColor: 'var(--md-sys-color-primary)',
    backgroundColor: 'color-mix(in srgb, var(--md-sys-color-primary) 40%, transparent)',
  } }
}

export const MaterialTextFieldDefaults = {
  MinWidth: MATERIAL_TEXT_FIELD_DIMENSIONS.minWidth,
  MinHeight: MATERIAL_TEXT_FIELD_DIMENSIONS.minHeight,
  shape: 'var(--md-sys-shape-corner-extra-small) var(--md-sys-shape-corner-extra-small) 0 0',
  roundedShape: 'var(--md-sys-shape-corner-medium)',
  FocusedIndicatorThickness: 2,
  UnfocusedIndicatorThickness: 1,
  colors: (overrides: MaterialTextFieldColors = {}) => ({ ...getMaterialTextFieldColors('filled'), ...overrides }),
  tonalColors: (overrides: MaterialTextFieldColors = {}) => ({ ...getMaterialTextFieldColors('filled', 'tonal'), ...overrides }),
  contentPaddingWithLabel: (overrides = {}) => ({ start: 16, top: 8, end: 16, bottom: 8, ...overrides }),
  contentPaddingWithoutLabel: (overrides = {}) => ({ start: 16, top: 16, end: 16, bottom: 16, ...overrides }),
  supportingTextPadding: (overrides = {}) => ({ start: 16, top: 4, end: 16, bottom: 0, ...overrides }),
} as const
export const MaterialOutlinedTextFieldDefaults = {
  ...MaterialTextFieldDefaults,
  shape: 'var(--md-sys-shape-corner-extra-small)',
  FocusedBorderThickness: 2,
  UnfocusedBorderThickness: 1,
  colors: (overrides: MaterialTextFieldColors = {}) => ({ ...getMaterialTextFieldColors('outlined'), ...overrides }),
  tonalColors: (overrides: MaterialTextFieldColors = {}) => ({ ...getMaterialTextFieldColors('outlined', 'tonal'), ...overrides }),
} as const
